// Generated by https://quicktype.io

class Actor {
  bool adult;
  int gender;
  int id;
  String name;
  String originalName;
  double popularity;
  String profilePath;
  int castId;
  String character;
  String creditId;
  int order;
  String job;

  Actor({
    this.adult,
    this.gender,
    this.id,
    this.name,
    this.originalName,
    this.popularity,
    this.profilePath,
    this.castId,
    this.character,
    this.creditId,
    this.order,
    this.job,
  });
  Actor.fromJsonMap(Map<String, dynamic> json) {
    adult = json['adult'];
    gender = json['gender'];
    id = json['id'];
    name = json['name'];
    originalName = json['original_name'];
    popularity = json['popularity'];
    profilePath = json['profile_path'];
    castId = json['cast_id'];
    character = json['character'];
    creditId = json['credit_id'];
    order = json['order'];
    job = json['job'];
  }

  getPhoto() {
    if (profilePath == null) {
      return 'https://www.google.com/url?sa=i&url=https%3A%2F%2Fcrowd-literature.eu%2Fspeakers%2Fno-avatar%2F&psig=AOvVaw2CUztJhuRaIYR23aVV3_Hh&ust=1612610042485000&source=images&cd=vfe&ved=0CAIQjRxqFwoTCLDcgdzO0u4CFQAAAAAdAAAAABAD';
    } else {
      return 'https://image.tmdb.org/t/p/w500/$profilePath';
    }
  }
}
//aquí para manejar la lista de actores, podría hacerse
//en otro sitio

class Cast {
  List<Actor> actores = new List();

  Cast.fromJsonList(List<dynamic> jsonList) {
    if (jsonList == null) {
      return;
    }

    jsonList.forEach((act) {
      final actor = Actor.fromJsonMap(act);
      actores.add(actor);
    });
  }
}
